# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false
neogradle.subsystems.decompiler.maxMemory=4G
neogradle.subsystems.recompiler.maxMemory=4G
neogradle.subsystems.parchment.minecraftVersion=1.21.0
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

minecraft_version=1.21.1
parchment_version=2024.11.17
minecraft_version_range=[1.20.6,1.21.2)
neo_version=21.1.210
neo_version_range=[21,)
loader_version_range=[2,)
mod_id=eidolon_repraised
mod_version=0.5.0.0-pre14
ars_version=5.11.0.1272
jei_version=19.21.0.247
emi_version=1.1.19+1.21.1
curios_version=9.5.1
geckolib_version=4.6.6
lodestone_version=1.7.1.344
malum_version=1.7.3.2