modLoader = "javafml" #mandatory
loaderVersion = "[42,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
issueTrackerURL = "https://github.com/Alexthw46/Eidolon-Repraised/issues" #optional
[[mods]] #mandatory
modId = "eidolon" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Eidolon:Repraised" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
logoFile = "logo.png" #optional
credits = "elucent as the original creator and maker of most of the assets" #optional
authors = "elucent up to 0.3.0, currently maintained by Alexthw" #optional
description = '''
A spooky magic mod about necromancy. Now with a touch of opposing light!
'''
[[dependencies.eidolon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2, 1.19.3)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.eidolon]]
modId = "curios"
mandatory = true
versionRange = "[1.19-5.0.7.1,)"
ordering = "AFTER"
side = "BOTH"