name: Publish action

on:
  workflow_dispatch:
    branches: [ "1.19.2" ]
    inputs:
      version:
        description: 'Mod Version'
        required: true
        type: string
      changelog:
        description: 'Changes'
        required: true
        type: string

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 870250
          modrinth-id: eWX2m1eM
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: forge
          name: Eidolon:Repraised ${{ env.MINECRAFT_VERSION }}-${{ inputs.version }}
          version:  eidolon_repraised-${{ env.MINECRAFT_VERSION }}-${{ inputs.version }}
          game-versions: |
            ${{ env.MINECRAFT_VERSION }}
          changelog: ${{inputs.changelog}}
          version-resolver: exact
