name: Publish action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod Version'
        required: true
        type: string
      version_type:
        description: 'Version Type'
        required: true
        type: choice
        default: release
        options:
        - alpha
        - beta
        - release
      changelog:
        description: 'Changes'
        required: true
        type: string

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  MC_MIN_VER: '1.21'
  MC_MAX_VER: '1.21.1'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up JDK ${{ env.JAVA_VERSION }}
       uses: actions/setup-java@v4
       with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: |
            *.gradle
            gradle.*
            gradle/wrapper/gradle-wrapper.properties
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v4
     - name: make gradle wrapper executable
       if: ${{ runner.os != 'Windows' }}
       run: chmod +x ./gradlew
     - name: Build with Gradle
       run: ./gradlew build
     - uses: actions/upload-artifact@v4
       with:
          name: all-jar
          path: build/libs/*-all.jar
     - uses: actions/upload-artifact@v4
       with:
          name: sources-jar
          path: build/libs/*-sources.jar
     - uses: Kir-Antipov/mc-publish@v3.3
       with:
          curseforge-id: 870250
          modrinth-id: eWX2m1eM
          modrinth-featured: true
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar
          version-type: ${{ inputs.version_type }}
          loaders: |
            neoforge
          name: Eidolon_:Repraised ${{ env.MINECRAFT_VERSION }}-${{ inputs.version }}
          version: ${{ inputs.version }}
          game-versions: |
            >=${{ env.MC_MIN_VER }} <=${{ env.MC_MAX_VER }}
          changelog: ${{inputs.changelog}}
